title: Nagihan Saka
description: 
theme: minima
footer:
  show_powered_by: false
favicon: /favicon.ico

header_pages:
  - nagihanca.md
  - strateji.md
  - sistem-dinamikleri.md
  - iletisim.md

collections:
  nagihanca:
    output: true
