title: Hakkımda
description: Oradan buradan şuradan düşüncelerim
theme: minima

header_pages:
  - nagihanca.md
  - strateji.md
  - sistem-dinamikleri.md
  - iletisim.md

collections:
  nagihanca:
    output: true
